log_level: debug
api_key: devkey
api_secret: secret
ws_url: livekit-server:7880
 
insecure: true
redis:
  address: redis-server:6379
  db: 10
s3:
  access_key: AWS_ACCESS_KEY
  secret: AWS_SECRET_KEY
  region: eu-west-3
  bucket: BUCKET_NAME