port: 7880
redis:
    address: redis-server:6379
    db: 10
rtc:
    udp_port: 7882
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 60000
    use_external_ip: true
keys:
    devkey: secret
logging:
    json: false
    level: info



